language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "592115019" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t 592115019/se234-lab10-backend .
- docker push 592115019/se234-lab10-backend
- docker pull 592115019/se234-lab10-client
script:
- docker-compose -H "$DOCKER_HOST" up -d 
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: EnDssg0MYaTRBLsvevp9JoE4KuUsbgB/fJLME306RkhzNNsqr+EOEka/uGA6/CJBYhbx9TjMtS69l1jEZW/g7MOdDzUOP5pBMhUCi78oSq7tT44pEzO/vZLYx3OdynjX6Zdat5Uwnetn5OGb0kyImfIEEMZiVet56kpKCLD8RuGUDn5BdsaQLyhRL/EWJMOu+CNolyLn8dGzpa7EtyBY36q4Qz65H4P0LYTZYeKCVlVjGtIWfFKjQfidBUIp3V9eArfOI23NAydKNVt00ha4oJCynbqAYNHEZihyVaMlOxRNPr7wUfyC5aIIX0jNcrtZgrXNPq04eL+N8PKGUfkTolv8kb5HkVmewNnM6rntufNmyw+vMMqlTfjm65yLN5VXkUgMyxGD0ZQ/w80aB3vhbfewGoQj7+cMqRBWHneBR/tsE7TuAoY63Je1sezjZGfXoX5K0XQqNosrpjlkU4lumdTutidP4uW6tq+W/gbFtAOEL+DFHyNLbYlnz2JTSSpjAvNLXxFh2mBrF2mAGRIWuxJXAr3ONydkD/y+5xhtZ4JTAsXQxoX76XeCiKl6w6+9WBUBa/56eM+Safd5p7vop/0y1oWbc1j85Y0TjtOWv/SwFujSyXK+eWzrQpyC7BIzTKSlJ3XvmXq94QThnxfsWLZRr3/TL/r/y2eAXKlhPnc=
  - secure: IHb6j9AhC+74afGwYlvXzlCGoeJUa+atD/bPiA8gVd5uo6tc+iZQYWe0c2ybExJDC2WCYMi+tP9rjMcn49kij1wY4dp7S+jBC29wYkWkQGmiWCNTSNYQonGTaG80UJTB2LSh/SLEo9LI1CHTfjWpuqduYh6G3NZmghwkfHhs1Y/iq1e/otrpFg3o3AOTJlHh2ntRo6sDEf4M4QgckpWN4HouuMeYV7srVnrwvdHJ0N9Xl+s27qSO2WuQ4RQriwD0zDQlXcSmQi8isOM1NMAUT+ZBPFj/Z5d9XcVO/bOOThlF8jkTxue5l9P362dmsNEi6C036xqoZ+nHT+Ic2SfcHbu62A00huhQqUP/yAlyNq4QPv7ucpIZeB2e00jYxgML1w1T8vwn3ToeM3TbQ6hve9OHdiW3qFkejJsvJSW1ljjRh6wOV+BQrnRiOgMfEd/KBJ7XTyEw/4AlW/Gyb8LGzw+WZZ4sp9ueFRGwBG36FPKxky+1gHcXZJCVPplPX2og0QdyQCwRcEy51GyAfaQpUsBNqdAH6LhqWsR8nOWfliofowsOfimCSTJ2HLh2xqYQsY/1RHgdMiDzCb6O01996zxPRl174D6vNW+rtI9XNg5VcsdhFEQ7DyGtYwlQcu6mHp2qKCN/1nepD/a4x9K/+zg3OBr9qTu3iId4LZ14X34=
  - secure: pwKqPzXD7QvGmApg7eHSXKyNN9Mm8nEEC5L6T1yvxs1m6SjqD/xosgTTN+ohxPoqJ4ZL7cPf9+11u8nbjHAp1m67/i+AdfRFWaIeqQPl+KdGBaa+IBUmNyB2oQ9tnCQ7pfsKO8JZZH3+VlxL6f6Xpv5hhd0ozLhfwqAvg1NdLhTQ6+2QeqDaCGKW/P4VKyEPa0VS5nfL+iBaR05rWkzYe5amVStw8fmaB8bDNAces2e7RTNyJyCBwyXMlSkloZ2vDK48hvn0fzVr3DcEP5uNHc61saEW8rBiAmhK8aJvXIcijhocflAmG9DFqTBiPIPB+Qz+5XG3VtJAKstncmYh+QJDZlq/MS+MxF4meUNNmINLpYfpz+m44Y/M8AgoEzwgifpMACa2ejR3z+5pRWq2kX5IVD/zs0nINsXlr3xK5o/oXTyI6zQSZt3twNRmP/YPm1Rv0gpnDnGiNldvU7B4ePormYfWP6j8fbbHI4X2ZY0BM44p/ar49lf6KHkBtIYTQzcrKjdGxnqd3lWFRpWBRJWZO1FQSoR7xztJ37ujLL22ifXtcaqjLeHzgH+LtH5ighzYz1NVVrC59Wv+VlwdRLsMbky0MbqNJHsDEmlyZGt5XqOBILxb3yOmaHd07UGgaRornAhaBn0fVqn7r68C26mEelxnWnT2GS7U9lP/KwQ=
