language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -u "592115019" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/backend.jar -t 592115019/se234-lab10-backend
  .
- docker push 592115019/se234-lab10-backend
- docker pull 592115019/se234-lab10-client
script:
- docker-compose -H "tcp://54.186.240.231:5019" up -d
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    secure: lLvMu02Dmh6ULrH8A8LdQpjZAc7rdinFtz3Njap+h1xls6fj8x4v/wfEwoXQ9PxsBBiqxQAQjuGb6t4tY1h2sfYLYl4fOLt49/gPfkXyevWGJc2S3+roBtd8JpsVMX2OgVFbkRPsPaKi7Y1i2FGHeiipdgXylFvIUGQVAOlqPxNTa68XMzSBH1I/+0QyIQG199w6L/4WDAoKMPNm0fgKw8y/DAgCYnP08rfVQySnr/zKUzE1o/eMHQ+wFycw0kPtHJkD1L7+0SeNRHjAc+COlYuMd54KHU/54RDaov9c7EhRImEoI1HN6KJfimyzSCJra3ThlTbtGbDxMDbYGiuTuNerjB0aRo4CIag5G7Cj5AVgzNg2+6htK06gbg7K4xzZZHU3O1yBG9zCMVbmb9nt9VqqhXS1v24/lpPwr8fR/z2jW9dMyqy2I4xc5KPiqO9f9v7mG6Y7eIGxC03/21IyHA9DUVRP3YrBwGbBWL3pIc7HIHiSFJcc2nDf/57Wj7OeOQ7riA+putr4myryzzqQoQwDIfkHgrj2LCy8hFGU5KZm9tPj0AFlBY305OLDEHxEFAA26ki4JFmM/wIRhFZZ1LLgVXusgQCL/O4pvA8xcXtHefmbIIFGb7as0Ai5/R++oeAQkErTxK2QcBtuNutnO9xCpFSYtiCRpG3QhtJ5KiQ=
